import Head from 'next/head';
import SkillCategory from "../components/skill-category";
import Experience from "../components/experience";
import Education from "../components/education";

import {education} from "../json/education";
import {experience} from "../json/experience";
import {skills} from "../json/skills";

export async function getStaticProps(context) {
    return {
        props: {
            education,
            experience,
            skills
        }
    }
}

export default function Home() {
  return (
      <div className={'bg-secondary'}>
        <Head>
          <title>NextJS Portfolio</title>
          <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
        </Head>
        <main>
            <div className="container mx-auto prose lg:prose-xl px-8 py-8 md:px-0 md:py-16">
                <div className={'border border-solid border-primary p-8 my-8 md:p-16 md:my-16'}>
                    <h2 className={'text-primary'}>Skills</h2>
                    {skills.map((item) => (
                        <SkillCategory key="{item}" item={item}></SkillCategory>
                    ))}
                </div>
                <div className={'border border-solid border-primary p-8 my-8 md:p-16 md:my-16'}>
                    <h2 className={'text-primary'}>Work experience</h2>
                    <div className={''}>
                        {experience.map((item) => (
                            <Experience key="{item}" item={item}></Experience>
                        ))}
                    </div>
                </div>
                <div className={'border border-solid border-primary p-8 my-8 md:p-16 md:my-16'}>
                    <h2 className={'text-primary'}>Education</h2>
                    <div className={''}>
                        {education.map((item) => (
                            <Education key="{item}" item={item}></Education>
                        ))}
                    </div>
                </div>
            </div>
        </main>
      </div>
  );
}
