import {GRAPH_TOKEN, GRAPH_URL} from '../lib/constants';

import Head from 'next/head';
import SkillCategory from "../components/skill-category";
import Experience from "../components/experience";
import Education from "../components/education";


function Home({educationCollection, experienceCollection, skillsCollection}) {
    return (
        <div className={'bg-secondary'}>
            <Head>
                <title>NextJS Portfolio</title>
                <meta name='description' content='Generated by create next app'/>
                <link rel='icon' href='/favicon.ico'/>
            </Head>
            <main>
                <div className="container mx-auto prose lg:prose-xl px-8 py-8 md:px-0 md:py-16">
                    <div className={'border border-solid border-primary p-8 my-8 md:p-16 md:my-16'}>
                        <h2 className={'text-primary'}>Skills</h2>
                        {skillsCollection.map((item) => (
                            <SkillCategory key="{item}" item={item}></SkillCategory>
                        ))}
                    </div>
                    <div className={'border border-solid border-primary p-8 my-8 md:p-16 md:my-16'}>
                        <h2 className={'text-primary'}>Work experience</h2>
                        <div className={''}>
                            {experienceCollection.map((item) => (
                                <Experience key="{item}" item={item}></Experience>
                            ))}
                        </div>
                    </div>
                    <div className={'border border-solid border-primary p-8 my-8 md:p-16 md:my-16'}>
                        <h2 className={'text-primary'}>Education</h2>
                        <div className={''}>
                            {educationCollection.map((item) => (
                                <Education key="{item}" item={item}></Education>
                            ))}
                        </div>
                    </div>
                </div>
            </main>
        </div>
    );
}

export async function getStaticProps(context) {
    try {
        const headers = {
            'content-type': 'application/json',
            'Authorization': `Bearer ${GRAPH_TOKEN}`
        };
        const requestBody = {
            query: `query {
              skillCategoryCollection(limit: 20) {
                items {
                  title,
                  skillCollection(limit: 20) {
                    items {
                        title,
                        rating
                    }
                  }
                }
              }
              educationCollection(limit: 20) {
                  items {
                      title,
                      location,
                      from,
                      till,
                      level,
                      description
                  }
              }
              experienceCollection(limit: 20) {
                  items {
                      title,
                      type,
                      location,
                      from,
                      till,
                      description,
                      clientsCollection(limit: 20) {
                          items {
                              title
                          }
                      }
                  }
              }
            }`
        };

        const options = {
            method: 'POST',
            headers,
            body: JSON.stringify(requestBody)
        };

        const response = await (await fetch(GRAPH_URL, options)).json();
        console.log('RESPONSE FROM FETCH REQUEST', response?.data);

        const educationCollection = response?.data.educationCollection?.items;
        const experienceCollection = response?.data.experienceCollection?.items;
        const skillsCollection = response?.data.skillCategoryCollection?.items;

        return {
            props: {
                educationCollection,
                experienceCollection,
                skillsCollection
            }
        }
    } catch (err) {
        console.log('ERROR DURING FETCH REQUEST', err);
    }
}

export default Home;
